name: Deploy Workflow
on:
  push:
    branches:
      - master
jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/phpunit
  deploy:
    needs: [app-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/phpunit
      - name: Remove exisiting builds
        run: rm -r ./builds/*
      - name: Build a new executable
        run: php psb app:build --build-version=0.0.1
      - name: Commit executable to the repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build new executable
          file_pattern: psb
          repository: ./builds

